# Generated by Django 4.2.4 on 2023-08-17 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_passengers', models.PositiveIntegerField()),
                ('departure_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('destination_id', models.AutoField(primary_key=True, serialize=False)),
                ('destination_name', models.CharField(max_length=255)),
                ('destination_photo_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Planets',
            fields=[
                ('planet_id', models.AutoField(primary_key=True, serialize=False)),
                ('planet_name', models.CharField(max_length=255)),
                ('planet_photo_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spaceships',
            fields=[
                ('spaceship_id', models.AutoField(primary_key=True, serialize=False)),
                ('spaceship_name', models.CharField(max_length=255)),
                ('spaceship_photo_link', models.URLField(blank=True, null=True)),
                ('seating_capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('profile_photo_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeatingArrangement',
            fields=[
                ('arrangement_id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_number', models.CharField(max_length=10)),
                ('availability', models.BooleanField(default=True)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bookings')),
                ('spaceship_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.spaceships')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_number', models.CharField(max_length=255)),
                ('card_expiry', models.CharField(max_length=10)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
        migrations.CreateModel(
            name='PassengerEmails',
            fields=[
                ('email_id', models.AutoField(primary_key=True, serialize=False)),
                ('passenger_email', models.EmailField(max_length=254)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bookings')),
            ],
        ),
        migrations.CreateModel(
            name='FlightSchedules',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('departure_datetime', models.DateTimeField()),
                ('arrival_datetime', models.DateTimeField()),
                ('flight_photo_link', models.URLField(blank=True, null=True)),
                ('departure_planet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='app.planets')),
                ('destination_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='app.destinations')),
                ('flight_group_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.flightschedules')),
                ('spaceship_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.spaceships')),
            ],
        ),
        migrations.AddField(
            model_name='destinations',
            name='planet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.planets'),
        ),
        migrations.CreateModel(
            name='BookingStoppings',
            fields=[
                ('booking_stopping_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bookings')),
                ('stop_destination_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.destinations')),
                ('stop_planet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.planets')),
            ],
        ),
        migrations.AddField(
            model_name='bookings',
            name='destination_planet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_planets', to='app.planets'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='payment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paymentmethods'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='schedule_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.flightschedules'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='spaceship_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.spaceships'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='starting_planet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_planets', to='app.planets'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users'),
        ),
    ]
