# Generated by Django 4.2.4 on 2023-08-17 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Planets',
            new_name='Planet',
        ),
    ]
