# Generated by Django 4.2.4 on 2023-08-18 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_planets_planet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethods',
            name='user_id',
        ),
    ]
