# Generated by Django 4.2.4 on 2023-08-18 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_paymentmethods_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethods',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.users'),
            preserve_default=False,
        ),
    ]
