# Generated by Django 4.2.4 on 2023-08-20 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_bookings_booking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seat_id', models.AutoField(primary_key=True, serialize=False)),
                ('availability', models.BooleanField(default=True)),
                ('booking_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.booking')),
                ('spaceship_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.spaceships')),
            ],
        ),
        migrations.RemoveField(
            model_name='flightschedule',
            name='flight_group_id',
        ),
        migrations.DeleteModel(
            name='SeatingArrangement',
        ),
    ]
