# Generated by Django 4.2.4 on 2023-08-20 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_seat_remove_flightschedule_flight_group_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planet',
            name='planet_photo_link',
        ),
        migrations.RemoveField(
            model_name='spaceships',
            name='spaceship_photo_link',
        ),
    ]
