# Generated by Django 4.2.4 on 2023-08-20 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_destinations_destination_photo_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightschedule',
            name='flight_photo_link',
        ),
    ]
