# Generated by Django 4.2.4 on 2023-08-20 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_booking_departure_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='departure_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='destination',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='spaceship_company',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='spaceship_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='starting_planet',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spaceships',
            name='company',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
